#!/bin/bash
homepath=$HOME
musicpath=$homepath/Music
videopath=$homepath/Videos
if [[ ! -d $homepath/.cache/YTdownload/final ]]
then 
	mkdir -p $homepath/.cache/YTdownload/final
fi
cachepath=$homepath/.cache/YTdownload
cd $cachepath
echo "# Netscape HTTP Cookie File
# This file is generated by youtube-dl --cookies cookies.txt.  Do not edit.

.youtube.com	TRUE	/	FALSE	1676711960	APISID	Ek7kAibmsIzBf8GM/AhDI2zdN7XsPxn1I8
.youtube.com	TRUE	/	FALSE	1676711960	HSID	APOh8YJyS7smaYIlk
.youtube.com	TRUE	/	TRUE	1634701660	PREF	f6=80&tz=Asia.Kolkata
.youtube.com	TRUE	/	TRUE	1676711960	SAPISID	j3HPFl39CbWfqyhP/AFaLRaHdgchtayKXu
.youtube.com	TRUE	/	FALSE	1676711960	SID	6gfXcNQRh4gFg3TpLyESD6d69Xs5mDQQoumnIOxxIMn5WzaXxA35m7WaxaiDvNZ04SvYmg.
.youtube.com	TRUE	/	FALSE	1645199680	SIDCC	AJi4QfFOs9HfR4FoIFQ5QuTqnRJ21_DLw8P4QZO7NdSfNZ2jPtv9ZHoVoRiWEDk4lTnCPs_xjw
.youtube.com	TRUE	/	TRUE	1676711960	SSID	AhOZJ2iBCMKKLqMp_
.youtube.com	TRUE	/	TRUE	1629194039	VISITOR_INFO1_LIVE	KIUCbX1OyBo
.youtube.com	TRUE	/	TRUE	0	YSC	l-BFCM7Ra9s
.youtube.com	TRUE	/	TRUE	1676711960	__Secure-3PAPISID	j3HPFl39CbWfqyhP/AFaLRaHdgchtayKXu
.youtube.com	TRUE	/	TRUE	1676711960	__Secure-3PSID	6gfXcNQRh4gFg3TpLyESD6d69Xs5mDQQoumnIOxxIMn5WzaXvr6G6HZX-unzIzDvPifPsg.
.youtube.com	TRUE	/	TRUE	1645199680	__Secure-3PSIDCC	AJi4QfG6-po5Qu6HMaxBMqneahQJeerc-ShJSgKXNOjsgHlK-KVLRyEoDl40dF1R4pXck0NRDA
" > cookies.txt

function show_help(){
echo "USAGE: ytd {Argument} [URL] or --clipboad
ytd [URL] direct use a youtube URL	
    -c, --clipboard For using clipboard to get a youtube URL
	-n, --not-youtube [URL] For using non youtube URL as input
	-h or --help For show this help"
}
function wr_arg(){
echo "ERROR: argument '$1' isn't valid or URL input not given"
}
function download_song(){
	url=$1
	name=$2
	echo Downloading....
	youtube-dl --cookies cookies.txt -x --write-thumbnail --audio-quality 0 --audio-format mp3 --add-metadata -o "$name.%(ext)s" $url
	convert -quiet -define jpg:size=720x720 "$name.*"  -thumbnail 720x720^ -gravity center -extent 720x720 final/"$name.jpg" 2>/dev/null
	ffmpeg -nostats -loglevel 0 -i "$name.mp3" -i final/"$name.jpg" -map 0:0 -map 1:0 -c:a copy -id3v2_version 3 -metadata:s:v title="Album cover" -metadata:s:v comment="Cover (front)" $musicpath/"$name.mp3" >/dev/null
	rm -f final/"$name".* "$name".* 
}
function download_music(){
	url=$1
	echo "Input URL: $url"
	case $url in
	*playlist*) 
				#youtube playlist download script
				echo "This is a youtube music playlist URL"  
				youtube-dl --cookies cookies.txt -e $url > listsongsplaylist
				sed -i 's/\"//g' listsongsplaylist
				echo "Matching playlist songs to your library"
				youtube-dl --cookies cookies.txt --get-id $url > listurl
				n=0
				while read psname
				do
			 		echo $psname
			 		((n++))
			 	if [[ ! -r $musicpath/"$psname.mp3" ]]
			 	then
					urlnew=$(awk "NR==$n" listurl)
					download_song $urlnew "$psname"
				else
               		echo "Song already exist in your library"
                	continue
			 	fi
				done < listsongsplaylist
				rm listsongsplaylist listurl
				;;
	*)
		#single song download script
		echo "This is a youtube music URL"
		youtube-dl --cookies cookies.txt -e $url > name
		sed -i 's/\"//g' name
		name=$(cat name)
		rm name
		echo $name
		if [[ ! -r $musicpath/"$name.mp3" ]]
		then 
			download_song $url "$name" $musicpath
		else
			echo "Song already exist in your library" 
		fi
		;;
	esac
}
function download_video(){
	url=$1
	echo "This is a youtube video URL"
	name=$(youtube-dl --cookies cookies.txt -e $url)
	echo "Video title: $name" 
	echo "Fetching all formats"
	youtube-dl --cookies cookies.txt -F $url         
	echo "Select a format code and type:"
	read format
	echo Downloading.......
	youtube-dl --cookies cookies.txt -f $format+bestaudio -o $videopath/'%(title)s.%(ext)s' $url
}
function case_url(){
	case $1 in
	*music.youtube.com*)
						download_music $1 ;;
	*www.youtube.com*)
	
						download_video $1 ;;
	*youtu.be*)
				download_video $1 ;;
	*)
		echo 'Clipboard content not looks lika a youtube URL'
		show_help ;;
	esac
}


case $1 in
	-c)
		clip=$(wl-paste)
		case_url $clip ;;
	--clipboad)
		 clip=$(wl-paste)
		case_url $clip ;;
	-n)
		if [[ ! -z $2 ]]
		then
			nyurl=$2
		else
			wr_arg
			show_help
		fi ;;
	--not-youtube)
		if [[ ! -z $2 ]]
		then
			nyurl=$2
		else
			wr_arg
			show_help 
		fi ;;
	-h)
		show_help ;;
	--help)
		show_help ;;
	*music.youtube.com*)
						download_music $1 ;;
	*www.youtube.com*)
	
						download_video $1 ;;
	*youtu.be*)
				download_video $1 ;;
	*)
		show_help ;;
esac

exit 0

#dependecies python pip youtube-dl ffmpeg xclip/wl-clipboard imagemagick 
